[project]
name = "dron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopy>=2.4.1",
    "matplotlib>=3.10.3",
    "requests>=2.32.3",
    "routeros-api>=0.21.0",
    "shapely>=2.1.1",
]
